

###
GET http://localhost:8080/api/appUsers/2/houses
Accept: application/json


###
GET http://localhost:8080/api/houses/byOwner/3
Accept: application/json

###
GET http://localhost:8080/api/appUser/allAppUsers
Accept: application/json

###
GET http://localhost:8080/api/appUser/allAppUsers
Accept: application/json


###
PATCH http://localhost:8080/api/appUser/5
Accept: application/json
Content-Type: application/json

{
  "name": "fas"
}

###
GET http://localhost:8080/api/houses/4/houses
Accept: application/json